Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
