Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: percent

Style/FormatStringToken:
  EnforcedStyle: unannotated

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma



Lint/AmbiguousRegexpLiteral:
  Enabled: false
